Fix smiley viewer script so that it runs without errors
vanilla/nbbc pull request #11
Opened 2017-05-23 23:11 UTC by djmattyg007

2017-06-05 20:56 UTC, DaazKu requested changes

2017-06-05 20:56 UTC, DaazKu commented on tools/collect_smileys.php
> -<base href="<?php print "http://" . $_SERVER['SERVER_NAME'] . dirname(dirname($_SERVER['REQUEST_URI'])); ?>" />
This line should not be removed. 

See https://github.com/vanilla/nbbc/pull/11/files#diff-028043b7bd7f006af37bbd7f9649a099R29

2017-06-05 22:38 UTC, djmattyg007 commented on tools/collect_smileys.php
> -<base href="<?php print "http://" . $_SERVER['SERVER_NAME'] . dirname(dirname($_SERVER['REQUEST_URI'])); ?>" />
Did you mean to link somewhere else? Right now you're linking to this diff.

2017-06-06 14:12 UTC, DaazKu commented on tools/collect_smileys.php
> -<base href="<?php print "http://" . $_SERVER['SERVER_NAME'] . dirname(dirname($_SERVER['REQUEST_URI'])); ?>" />
Seems like github doesn't auto expand the code.
https://github.com/djmattyg007/nbbc/blob/820e64739b6d6923f160d0201384bd0663889e88/tools/collect_smileys.php#L29

2017-06-06 22:28 UTC, djmattyg007 commented
I removed the line because I erroneously assumed the `<base>` tag only affected `<a>` tags. I'll put it back in, thanks for raising it.

2017-06-15 20:18 UTC, DaazKu approved these changes

2017-06-15 20:18 UTC, merged