Fix deprecation warnings in PHP 8.1
vanilla/nbbc pull request #24
Opened 2021-12-31 00:38 UTC by hemberger

According to the PHP 8.1 changelog:

> Passing null to non-nullable internal function parameters is
> deprecated.

There are a handful of places in BBCode.php that pass null to the
`strlen` function, which results in the following warnings:

> Deprecated: strlen(): Passing null to parameter #1 ($string) of
> type string is deprecated

This affects 3 functions:

1) cleanupWSByPoppingStack
2) cleanupWSByEatingInput
3) cleanupWSByIteratingPointer

In the cases of 1) and 2), passing `$pattern = null` is a no-op, and
therefore we can safely omit these calls entirely. This is because we
immediately trigger the condition:

    if (strlen($pattern) <= 0)
        return;

In the case of 3), passing `$pattern = null` returns the 2nd argument
passed to the function, so we can simply use this value directly
instead. This is because we immediately trigger the condition:

    if (strlen($pattern) <= 0)
        return $pos;

These changes should fix the deprecation warnings, because we will no
longer pass null to `strlen`, while also leaving the logic unchanged.

2022-01-05 17:16 UTC, tburry requested changes
I've merged CI into master. If you could rebase onto master that would be a help.

If you run the tests on your localhost you'll actually see that they fail on PHP 8 even. Is there any possibility of you helping with those issues? There seems to be a logic issue now. There aren't any errors, but something isn't working anymore.

2022-01-05 19:05 UTC, hemberger commented
Hi @tburry, thanks for the quick update! This PR has been rebased against current master (though the Circle CI tests did not run, as you anticipated).

In my local testing, this PR passes the tests on all PHP versions that are enabled in Circle CI (7.2, 7.3, and 7.4). I see 3 failing tests for PHP 8.0, but those same 3 tests fail for current master as well. Quite a few more tests fail for PHP 8.1 (16 in total).

I would be happy to help fix the general issues with PHP 8+, if that's what you're asking. If so, I'll make a separate PR for the PHP 8.0 fixes, and then I can work on PHP 8.1. Does that sound good to you?

2022-01-05 19:42 UTC, seanofw commented
So — as the original author of NBBC, I should probably weigh in on this and talk a little about the *intent* of the design, which might help a little to figure out why the tests are failing.  The *intent* has gotten very muddied in recent versions of the code.

Consider this example, from lines 1596-1604:

```php
        if (isset($this->tag_rules[$tag_name]) && isset($this->tag_rules[$tag_name]['after_tag'])) {
            $newpos = $this->cleanupWSByIteratingPointer(
                isset($this->tag_rules[$tag_name]['after_tag']) ? $this->tag_rules[$tag_name]['after_tag'] : null,
                $pos + 1,
                $this->stack
            );
        } else {
            $newpos = $this->cleanupWSByIteratingPointer(null, $pos + 1, $this->stack);
        }
```

In the current form of the code, it's not *really* obvious what's going on here or why, because it's buried in syntax that earlier versions of PHP forced on us.  When I first wrote it, that code looked something like this:

```php
$newpos = $this->cleanupWSByIteratingPointer(@$this->tag_rules[$tag_name]['after_tag'], $pos + 1, $this->stack);
```

Which is to say, all of those `isset()` tests really are just there to perform null-propagation:  If there's no rule, no `after_tag` condition, or whatever, we just pass `null` down as the rule but *still execute the cleanup function*.

The cleanup functions are supposed to *always* execute, but sometimes they boil down to no-ops depending on the data passed in.  That makes them much easier to reason about, and it's much easier to prove the overall logic correct.  In more recent versions of PHP they got wrapped in `if` tests instead of just having the `@` shut-up operator there, and so that design intent got lost.

My guess is that somewhere in the refactor in this PR, some subtle thing changed such that one of the clauses no longer does the same thing it previously did, which is why the tests are no longer passing.  So I'd recommend, then, that instead of trying to factor out special cases in the `if` clauses and avoid calling the cleanup functions altogether, to use things like `?...:` and the new `??` operator to inch closer to the original design:  To always invoke the cleanup functions, but then just be slightly smarter inside them about what to do if a `null` or other unusual cases are passed in.  That allows the callers' logic to become simpler and closer to the original design, and likely more correct (and more likely to pass the unit tests, too!).

Ultimately, it's up to folks working on this now to decide how to maintain it, whether to use the original design or to use a revised one instead; but I thought I'd at least offer a little advice to explain how it was originally *supposed* to work.

2022-01-05 20:16 UTC, hemberger commented
Hi @seanofw, thanks for your insight! I should clarify that this PR doesn't actually break any tests (in fact there should be no functionality changes whatsoever). The tests are broken, even in current master, due to changes in the PHP language and standard library introduced in PHP 8.0 and 8.1.

That said, it's extremely valuable to understand the original motivations of the code as we (or, rather, the people maintaining this fork) decide how to add support for new PHP versions. I agree that always calling the cleanup functions, regardless of whether or not they are a no-op, seems preferable. In that case, we just need to make sure we're always passing strings when strings are expected, so it may be sufficient to replace `null` with the empty string. Would you like me to create an alternative PR to address this issue, so that you can assess which solution you prefer?

2022-01-06 14:03 UTC, tburry commented
Thanks so much for your help and input @hemberger and @seanofw. I'm just going to run this PR against the tests locally and merge it. I see another PR opened to fix the PHP 8 functionality. We can continue the fix/conversation there.

2022-01-06 14:05 UTC, tburry approved these changes

2022-01-06 14:05 UTC, merged